name: Run Bash Script

on: [workflow_dispatch]

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Bash script
      run: |
        chmod +x ./script.sh
        ./script.sh
